/**
 * Reproduction script for Plane issue #9329
 * "Inline work item creation shows generic error when title exceeds 255 characters"
 *
 * Generated by repro-agent on 2026-07-03
 * Target: Plane (localhost:3000)
 *
 * This is the REPLAY artifact — a deterministic Playwright test
 * that can be run N times to verify the bug state.
 */
import { test, expect } from "@playwright/test";

const PLANE_URL = process.env.PLANE_URL || "http://localhost:3000";
const PLANE_API = process.env.PLANE_API || "http://localhost:8000";
const EMAIL = process.env.PLANE_EMAIL || "admin@admin.com";
const PASSWORD = process.env.PLANE_PASSWORD || "qweQWE123!@#";
const WORKSPACE = process.env.PLANE_WORKSPACE || "plane-dev";

test.describe("Issue #9329: 255-char title validation", () => {
  test.beforeEach(async ({ page }) => {
    // Login flow: email → Continue → password → Go to workspace
    await page.goto(PLANE_URL);
    await page.waitForSelector('input[name="email"]');
    await page.fill('input[name="email"]', EMAIL);
    await page.click('button[type="submit"]');
    await page.waitForSelector('input[name="password"]');
    await page.fill('input[name="password"]', PASSWORD);
    await page.click('button[type="submit"]');
    await page.waitForURL(/.*\/plane-dev\//);
  });

  test("inline work item creation with 256-char title shows descriptive validation error, not generic error", async ({
    page,
  }) => {
    // Navigate to Seed Demo Project work items
    await page.goto(
      `${PLANE_URL}/${WORKSPACE}/projects/9e2a160f-a44f-4777-a761-564ab5e572a4/issues`
    );
    await page.waitForSelector("text=Work Items");

    // Click "Add work item" to open inline creation
    const addButton = page.locator("button", { hasText: "Add work item" });
    await addButton.click();

    // Wait for title input to appear
    const titleInput = page.locator('input[name="name"][placeholder="Title"]');
    await titleInput.waitFor({ state: "visible" });

    // Type 256 characters (exceeds 255 limit)
    const longTitle = "A".repeat(256);
    await titleInput.fill(longTitle);

    // Submit the form
    await titleInput.press("Enter");

    // Wait for validation response
    await page.waitForTimeout(2000);

    // ORACLE: Check for the validation message
    // Bug #9329 says: shows "Some error occurred. Please try again." (generic)
    // Expected fix: shows descriptive message about 255-char limit
    const validationMsg = page.locator(
      "text=Title should be less than 255 characters"
    );
    const genericError = page.locator("text=Some error occurred");

    const hasDescriptiveMsg = await validationMsg.isVisible().catch(() => false);
    const hasGenericError = await genericError.isVisible().catch(() => false);

    // Take evidence screenshot
    await page.screenshot({
      path: "reproductions/9329/evidence-playwright.png",
    });

    if (hasGenericError) {
      // BUG IS PRESENT — generic error shown instead of descriptive validation
      test.fail();
      expect(hasGenericError).toBe(false); // This will fail, confirming the bug
    }

    // If we reach here, the reported bug was NOT REPRODUCED (descriptive validation shown)
    expect(hasDescriptiveMsg).toBe(true);
  });

  test("API returns descriptive 400 error for 256-char title", async ({
    request,
  }) => {
    // Direct API validation test
    // First, get auth cookies by logging in via API
    const loginPage = await request.post(`${PLANE_URL}/`, {
      form: { email: EMAIL, password: PASSWORD },
    });

    const longTitle = "A".repeat(256);
    const response = await request.post(
      `${PLANE_API}/api/workspaces/${WORKSPACE}/projects/9e2a160f-a44f-4777-a761-564ab5e572a4/issues/`,
      {
        data: { name: longTitle },
        headers: { "Content-Type": "application/json" },
      }
    );

    expect(response.status()).toBe(400);
    const body = await response.json();
    expect(body.name).toBeDefined();
    expect(body.name[0]).toContain("255");
  });
});
