/**
 * Reproduction script for Plane issue #9329
 * "Inline work item creation shows generic error when title exceeds 255 characters"
 *
 * Generated by repro-agent on 2026-07-03
 * Target: Plane (localhost:3000)
 *
 * REPLAY ARTIFACT — deterministic Playwright test, no agent, no LLM.
 * Run: npx playwright test reproductions/9329/repro.spec.ts
 *
 * Verdict language: REPRODUCED / NOT REPRODUCED (never "FIXED")
 */
import { test, expect } from "@playwright/test";

const EMAIL = process.env.PLANE_EMAIL || "admin@admin.com";
const PASSWORD = process.env.PLANE_PASSWORD || "qweQWE123!@#";
const WORKSPACE = "plane-dev";
const PROJECT_ID = "9e2a160f-a44f-4777-a761-564ab5e572a4";

test.describe("Issue #9329: 255-char title validation", () => {
  // Generous timeout — Plane login + navigation can be slow
  test.setTimeout(90_000);

  test.beforeEach(async ({ page }) => {
    // Login flow: email → Continue (wait) → password → Go to workspace (wait)
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    // Step 1: Email
    const emailInput = page.locator('input[name="email"]');
    await emailInput.waitFor({ state: "visible", timeout: 15_000 });
    await emailInput.fill(EMAIL);
    await page.locator('button[type="submit"]').click();

    // Step 2: Password (appears after Continue)
    const passwordInput = page.locator('input[name="password"]');
    await passwordInput.waitFor({ state: "visible", timeout: 15_000 });
    await passwordInput.fill(PASSWORD);
    await page.locator('button[type="submit"]').click();

    // Wait for workspace to load
    await page.waitForURL(`**/${WORKSPACE}/**`, { timeout: 30_000 });
  });

  test("inline work item creation with 256-char title shows descriptive validation error, not generic error", async ({
    page,
  }) => {
    // Navigate to Seed Demo Project work items
    await page.goto(`/${WORKSPACE}/projects/${PROJECT_ID}/issues`);
    await page.waitForLoadState("networkidle");

    // Click "Add work item" to open inline creation
    const addButton = page.locator("button", { hasText: "Add work item" });
    await addButton.waitFor({ state: "visible", timeout: 10_000 });
    await addButton.click();

    // Wait for title input to appear
    const titleInput = page.locator('input[name="name"]');
    await titleInput.waitFor({ state: "visible", timeout: 10_000 });

    // Type 256 characters (exceeds 255 limit)
    const longTitle = "A".repeat(256);
    await titleInput.fill(longTitle);

    // Submit the form
    await titleInput.press("Enter");

    // Wait for validation response
    await page.waitForTimeout(3000);

    // ORACLE: Check for the validation message
    // Bug #9329 says: shows "Some error occurred. Please try again." (generic)
    // If descriptive message shown → NOT REPRODUCED
    // If generic error shown → REPRODUCED
    const validationMsg = page.locator(
      "text=Title should be less than 255 characters"
    );
    const genericError = page.locator("text=Some error occurred");

    const hasDescriptiveMsg = await validationMsg.isVisible().catch(() => false);
    const hasGenericError = await genericError.isVisible().catch(() => false);

    // Take evidence screenshot
    await page.screenshot({
      path: "reproductions/9329/evidence-replay.png",
      fullPage: true,
    });

    if (hasGenericError) {
      // REPRODUCED — the bug is present (generic error instead of descriptive)
      console.log("🐛 REPRODUCED: Generic error shown instead of descriptive validation");
      expect(hasGenericError).toBe(false);
    }

    // If we reach here, NOT REPRODUCED — descriptive validation shown
    console.log("⚪ NOT REPRODUCED: Descriptive validation message shown");
    expect(hasDescriptiveMsg).toBe(true);
  });
});
