/**
 * Artifact emitter — generates repro.spec.ts and verdict.md
 * from action-log.json and the reproduction verdict.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import type { ReproPlan, ActionLogEntry, Verdict } from "./repro-plan.schema.js";
import { PlaneAdapter } from "./plane-adapter.js";

const REPRODUCTIONS_DIR = "reproductions";

/**
 * Ensure the reproductions/<issue>/ directory exists.
 */
export function ensureReproDir(issueNumber: number): string {
  const dir = join(REPRODUCTIONS_DIR, String(issueNumber));
  mkdirSync(join(dir, "evidence"), { recursive: true });
  return dir;
}

/**
 * Write the repro-plan.json to disk.
 */
export function writePlan(issueNumber: number, plan: ReproPlan): string {
  const dir = ensureReproDir(issueNumber);
  const path = join(dir, "repro-plan.json");
  writeFileSync(path, JSON.stringify(plan, null, 2));
  return path;
}

/**
 * Append an action log entry.
 */
export function appendActionLog(
  issueNumber: number,
  entry: ActionLogEntry
): void {
  const dir = ensureReproDir(issueNumber);
  const path = join(dir, "action-log.json");
  let log: ActionLogEntry[] = [];
  if (existsSync(path)) {
    log = JSON.parse(readFileSync(path, "utf-8"));
  }
  log.push(entry);
  writeFileSync(path, JSON.stringify(log, null, 2));
}

/**
 * Generate verdict.md from the verdict and plan.
 */
export function writeVerdict(
  issueNumber: number,
  plan: ReproPlan,
  verdict: Verdict
): string {
  const dir = ensureReproDir(issueNumber);
  const path = join(dir, "verdict.md");

  const status = verdict.reproduced ? "✅ REPRODUCED" : "❌ NOT REPRODUCED";
  const md = `# Reproduction Verdict — #${plan.issue.number}

**Status:** ${status}
**Confidence:** ${verdict.confidence}
**Issue:** [${plan.issue.title}](${plan.issue.url})
**Bug class:** ${plan.bugClass}

## Reasoning

${verdict.reasoning}

## Steps Executed

${plan.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Evidence

- Screenshot: \`${verdict.evidenceFile}\`
- Action log: \`action-log.json\`
- Video: \`evidence/video.webm\`
`;

  writeFileSync(path, md);
  return path;
}

/**
 * Generate repro.spec.ts from action-log.json.
 * Claude Code calls this after a successful reproduction —
 * it reads the action log and translates browser-use agent steps
 * into Playwright equivalents.
 */
export function generateReproSpec(issueNumber: number): string {
  const dir = ensureReproDir(issueNumber);
  const logPath = join(dir, "action-log.json");
  const planPath = join(dir, "repro-plan.json");

  const log: ActionLogEntry[] = JSON.parse(readFileSync(logPath, "utf-8"));
  const plan: ReproPlan = JSON.parse(readFileSync(planPath, "utf-8"));

  // Build Playwright test body from action log
  const steps = log
    .map((entry) => {
      switch (entry.action) {
        case "navigate":
          return `  await page.goto('${entry.instruction}');`;
        case "act":
          return `  // Agent act: "${entry.instruction}"\n  // TODO: translate to Playwright selector action`;
        case "extract":
          return `  // Agent extract: "${entry.instruction}"`;
        case "observe":
          return `  // Agent observe: "${entry.instruction}"`;
        case "screenshot":
          return `  await page.screenshot({ path: 'evidence/replay-screenshot.png' });`;
        default:
          return `  // Unknown action: ${entry.action}`;
      }
    })
    .join("\n\n");

  const spec = `import { test, expect } from '@playwright/test';

/**
 * Reproduction test for issue #${plan.issue.number}
 * ${plan.issue.title}
 * ${plan.issue.url}
 *
 * Bug class: ${plan.bugClass}
 * Generated by repro-agent from action-log.json
 *
 * This test replays the exact steps the agent took to reproduce the bug.
 * No browser-use, no LLM — pure Playwright.
 */
test('reproduce #${plan.issue.number}: ${plan.issue.title}', async ({ page }) => {
  // Login — Plane uses a two-step flow: email → Continue → password → Go to workspace
  await page.goto('${PlaneAdapter.loginUrl}');
  await page.fill('input[name="email"]', '${PlaneAdapter.email}');
  await page.click('button:has-text("Continue")');
  await page.waitForSelector('input[type="password"]', { timeout: 10000 });
  await page.fill('input[type="password"]', '${PlaneAdapter.password}');
  await page.click('button:has-text("Go to workspace")');
  await page.waitForURL('**/${PlaneAdapter.workspace}/**');

  // Reproduction steps
${steps}
});
`;

  const specPath = join(dir, "repro.spec.ts");
  writeFileSync(specPath, spec);
  return specPath;
}

/**
 * Read the action log for an issue.
 */
export function readActionLog(issueNumber: number): ActionLogEntry[] {
  const path = join(REPRODUCTIONS_DIR, String(issueNumber), "action-log.json");
  if (!existsSync(path)) return [];
  return JSON.parse(readFileSync(path, "utf-8"));
}