/**
 * Reproduction script for Plane issue #9050
 * "Deleted stickies reappear on page reload"
 *
 * Generated by repro-agent on 2026-07-04
 * Target: Plane (localhost:3000)
 *
 * REPLAY ARTIFACT — deterministic Playwright test, no agent, no LLM.
 * Run: npx playwright test reproductions/9050/repro.spec.ts
 *
 * Verdict language: REPRODUCED / NOT REPRODUCED (never "FIXED")
 */
import { test, expect } from "@playwright/test";

const EMAIL = process.env.PLANE_EMAIL || "admin@admin.com";
const PASSWORD = process.env.PLANE_PASSWORD || "qweQWE123!@#";
const WORKSPACE = "plane-dev";

test.describe("Issue #9050: Deleted stickies reappear on reload", () => {
  // Generous timeout — Plane login + navigation can be slow
  test.setTimeout(90_000);

  test.beforeEach(async ({ page }) => {
    // Login flow: email → Continue (wait) → password → Go to workspace (wait)
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    // Step 1: Email
    const emailInput = page.locator('input[name="email"]');
    await emailInput.waitFor({ state: "visible", timeout: 15_000 });
    await emailInput.fill(EMAIL);
    await page.locator('button[type="submit"]').click();

    // Step 2: Password (appears after Continue)
    const passwordInput = page.locator('input[name="password"]');
    await passwordInput.waitFor({ state: "visible", timeout: 15_000 });
    await passwordInput.fill(PASSWORD);
    await page.locator('button[type="submit"]').click();

    // Wait for workspace to load
    await page.waitForURL(`**/${WORKSPACE}/**`, { timeout: 30_000 });
  });

  test("deleted sticky should not reappear after page reload", async ({
    page,
  }) => {
    const STICKY_TEXT = `REPRO-9050-${Date.now()}`;

    // ── 1. Navigate to stickies page ─────────────────────────
    await page.goto(`/${WORKSPACE}/stickies/`);
    await page.waitForLoadState("networkidle");

    // ── 2. Create a new sticky ───────────────────────────────
    // Look for "Add sticky" / "+" / "New sticky" button
    const addButton = page.locator(
      'button:has-text("Add"), button:has-text("New"), button:has-text("sticky"), button[aria-label*="add"], button[aria-label*="new"]'
    ).first();
    await addButton.waitFor({ state: "visible", timeout: 10_000 });
    await addButton.click();

    // Wait for sticky input/editor to appear and type the text
    await page.waitForTimeout(2000);

    // Try contenteditable (rich text) or textarea/input
    const stickyEditor = page.locator(
      '[contenteditable="true"], textarea, input[type="text"]'
    ).last();
    await stickyEditor.waitFor({ state: "visible", timeout: 10_000 });
    await stickyEditor.click();
    await stickyEditor.fill(STICKY_TEXT);

    // Click outside to save the sticky
    await page.locator("body").click({ position: { x: 10, y: 10 } });
    await page.waitForTimeout(2000);

    // ── 3. Verify the sticky was created ─────────────────────
    const stickyLocator = page.locator(`text=${STICKY_TEXT}`);
    await expect(stickyLocator.first()).toBeVisible({ timeout: 10_000 });

    // ── 4. Delete the sticky ─────────────────────────────────
    // Right-click on the sticky to open context menu
    await stickyLocator.first().click({ button: "right" });
    await page.waitForTimeout(1000);

    // Click "Delete" from the context/dropdown menu
    const deleteOption = page.locator(
      'button:has-text("Delete"), [role="menuitem"]:has-text("Delete"), div:has-text("Delete")'
    ).first();
    await deleteOption.waitFor({ state: "visible", timeout: 5_000 });
    await deleteOption.click();
    await page.waitForTimeout(1000);

    // Confirm deletion if a confirmation dialog appears
    const confirmButton = page.locator(
      'button:has-text("Delete"), button:has-text("Confirm"), button:has-text("Yes")'
    ).first();
    const hasConfirm = await confirmButton.isVisible().catch(() => false);
    if (hasConfirm) {
      await confirmButton.click();
    }
    await page.waitForTimeout(2000);

    // ── 5. Verify the sticky is gone ─────────────────────────
    await expect(stickyLocator).toHaveCount(0, { timeout: 10_000 });

    // ── 6. Reload the page ───────────────────────────────────
    await page.reload({ waitUntil: "networkidle" });
    await page.waitForTimeout(3000);

    // ── 7. Check if the sticky reappeared ────────────────────
    const reappearedCount = await stickyLocator.count();

    // ── 8. Take evidence screenshot ──────────────────────────
    await page.screenshot({
      path: "reproductions/9050/evidence-replay.png",
      fullPage: true,
    });

    // ── 9. Verdict ───────────────────────────────────────────
    if (reappearedCount > 0) {
      // REPRODUCED — the bug is present (deleted sticky came back)
      console.log(
        "🐛 REPRODUCED: Deleted sticky reappeared after page reload"
      );
      expect(
        reappearedCount,
        "Deleted sticky should NOT reappear after reload"
      ).toBe(0);
    }

    // If we reach here, NOT REPRODUCED — sticky stayed deleted
    console.log(
      "⚪ NOT REPRODUCED: Deleted sticky did not reappear after reload"
    );
    expect(reappearedCount).toBe(0);
  });
});
