/**
 * Reproduction script for Plane issue #9124
 * "Collapsible sub-tasks require three clicks to expand"
 *
 * Generated by repro-agent on 2026-07-04
 * Target: Plane (localhost:3000)
 *
 * REPLAY ARTIFACT — deterministic Playwright test, no agent, no LLM.
 * Run: npx playwright test reproductions/9124/repro.spec.ts
 *
 * Verdict language: REPRODUCED / NOT REPRODUCED (never "FIXED")
 */
import { test, expect } from "@playwright/test";

const EMAIL = process.env.PLANE_EMAIL || "admin@admin.com";
const PASSWORD = process.env.PLANE_PASSWORD || "qweQWE123!@#";
const WORKSPACE = "plane-dev";
const PROJECT_ID = "9e2a160f-a44f-4777-a761-564ab5e572a4";

test.describe("Issue #9124: Sub-task expand requires three clicks", () => {
  // Generous timeout — Plane login + navigation can be slow
  test.setTimeout(90_000);

  test.beforeEach(async ({ page }) => {
    // Login flow: email → Continue (wait) → password → Go to workspace (wait)
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    // Step 1: Email
    const emailInput = page.locator('input[name="email"]');
    await emailInput.waitFor({ state: "visible", timeout: 15_000 });
    await emailInput.fill(EMAIL);
    await page.locator('button[type="submit"]').click();

    // Step 2: Password (appears after Continue)
    const passwordInput = page.locator('input[name="password"]');
    await passwordInput.waitFor({ state: "visible", timeout: 15_000 });
    await passwordInput.fill(PASSWORD);
    await page.locator('button[type="submit"]').click();

    // Wait for workspace to load
    await page.waitForURL(`**/${WORKSPACE}/**`, { timeout: 30_000 });
  });

  test("sub-task expand/collapse chevron should respond on first click", async ({
    page,
  }) => {
    // Navigate to work items
    await page.goto(`/${WORKSPACE}/projects/${PROJECT_ID}/issues`);
    await page.waitForLoadState("networkidle");

    // Find an expand/collapse chevron indicating a task with sub-tasks
    // Chevrons are typically rendered as SVG icons or buttons near work items
    const chevron = page.locator(
      '[data-testid="expand-issue"], button:has(svg[class*="chevron"]), button:has(svg[class*="expand"]), [role="button"]:has(svg[class*="ChevronRight"]), [role="button"]:has(svg[class*="chevron"])'
    ).first();

    // Wait for work items to load and a chevron to appear
    await chevron.waitFor({ state: "visible", timeout: 15_000 });

    // ── Click 1: First click on the expand chevron ──
    await chevron.click();
    await page.waitForTimeout(2000);

    // Check if sub-tasks appeared after first click
    // Look for newly visible child items / nested rows
    const subTasksAfterClick1 = await page
      .locator('[data-testid="sub-issue"], [class*="sub-task"], [class*="subtask"], [class*="nested"], [class*="child-issue"]')
      .first()
      .isVisible()
      .catch(() => false);

    let clicksNeeded = 0;

    if (subTasksAfterClick1) {
      clicksNeeded = 1;
    } else {
      // ── Click 2: Second click ──
      await chevron.click();
      await page.waitForTimeout(2000);

      const subTasksAfterClick2 = await page
        .locator('[data-testid="sub-issue"], [class*="sub-task"], [class*="subtask"], [class*="nested"], [class*="child-issue"]')
        .first()
        .isVisible()
        .catch(() => false);

      if (subTasksAfterClick2) {
        clicksNeeded = 2;
      } else {
        // ── Click 3: Third click ──
        await chevron.click();
        await page.waitForTimeout(2000);

        const subTasksAfterClick3 = await page
          .locator('[data-testid="sub-issue"], [class*="sub-task"], [class*="subtask"], [class*="nested"], [class*="child-issue"]')
          .first()
          .isVisible()
          .catch(() => false);

        if (subTasksAfterClick3) {
          clicksNeeded = 3;
        }
      }
    }

    // Take evidence screenshot
    await page.screenshot({
      path: "reproductions/9124/evidence-replay.png",
      fullPage: true,
    });

    // ORACLE: Evaluate verdict
    if (clicksNeeded === 1) {
      // NOT REPRODUCED — expanded on first click as expected
      console.log("⚪ NOT REPRODUCED: Sub-task expanded on first click");
      expect(clicksNeeded).toBe(1);
    } else if (clicksNeeded >= 2) {
      // REPRODUCED — required multiple clicks to expand
      console.log(
        `🐛 REPRODUCED: Sub-task required ${clicksNeeded} clicks to expand (expected 1)`
      );
      expect(clicksNeeded, `Sub-task required ${clicksNeeded} clicks to expand, expected 1`).toBe(1);
    } else {
      // INCONCLUSIVE — could not determine if sub-tasks expanded
      console.log(
        "❓ INCONCLUSIVE: Could not determine if sub-tasks expanded after 3 clicks"
      );
      expect(clicksNeeded, "INCONCLUSIVE: Could not verify sub-task expansion").toBeGreaterThan(0);
    }
  });
});
